# Generated by Django 6.0.5 on 2026-05-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата відправки')),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення з сайту',
            },
        ),
        migrations.CreateModel(
            name='SurveyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100, verbose_name="Ім'я дитини")),
                ('parent_name', models.CharField(max_length=100, verbose_name="Ім'я одного з батьків")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('age_group', models.CharField(max_length=50, verbose_name='Вік дитини')),
                ('e_queue', models.CharField(max_length=10, verbose_name='Електронна черга')),
                ('format', models.CharField(max_length=50, verbose_name='Формат')),
                ('days', models.CharField(max_length=100, verbose_name='Дні тижня')),
                ('benefits', models.CharField(max_length=100, verbose_name='Пільги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкети (Заявки)',
            },
        ),
    ]
