# Generated by Django 6.0.5 on 2026-05-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
            ],
            options={
                'verbose_name': 'Питання (FAQ)',
                'verbose_name_plural': '3. Питання та Відповіді',
            },
        ),
        migrations.CreateModel(
            name='PageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default='Набір на 2026/2027 рік відкрито', max_length=100, verbose_name='Головна: Тег зверху')),
                ('hero_title', models.CharField(default='Простір де зростає щастя', max_length=200, verbose_name='Головна: Заголовок')),
                ('hero_desc', models.TextField(default='Сучасний заклад дошкільної освіти у Рівному. Ми поєднуємо професійний догляд, безпеку та інноваційні методики для гармонійного розвитку вашого малюка.', verbose_name='Головна: Опис')),
                ('about_title', models.CharField(default='Місце, де цікаво рости', max_length=200, verbose_name='Про нас: Заголовок')),
                ('about_desc', models.TextField(default='ЗДО №52 — це інноваційний простір безпечного розвитку. Наша головна мета — формування умов для гармонійного зростання вихованців та підтримка батьків у адаптації дитини.', verbose_name='Про нас: Опис')),
            ],
            options={
                'verbose_name': 'Тексти сторінок',
                'verbose_name_plural': '2. Тексти сторінок',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+38 (0362) 12-34-56', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(default='zdo52@ukr.net', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='м. Рівне, ЗДО №52', max_length=200, verbose_name='Адреса')),
                ('map_url', models.TextField(blank=True, default='[https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4359.132404903279!2d26.2602269765683!3d50.63693547162839!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x472f14ad48f32bbd%3A0xf6f285b3439b82dd!2z0KDRltCy0L3QtdC90YHRjNC60LjQuSDQlNCd0Jcg4oSWIDA1Mg!5e1!3m2!1suk!2sua!4v1779825928150!5m2!1suk!2sua](https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4359.132404903279!2d26.2602269765683!3d50.63693547162839!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x472f14ad48f32bbd%3A0xf6f285b3439b82dd!2z0KDRltCy0L3QtdC90YHRjNC60LjQuSDQlNCd0Jcg4oSWIDA1Mg!5e1!3m2!1suk!2sua!4v1779825928150!5m2!1suk!2sua)', verbose_name='Посилання на карту (тільки src з iframe Google Maps)')),
                ('facebook', models.URLField(blank=True, default='', verbose_name='Посилання на Facebook')),
                ('instagram', models.URLField(blank=True, default='', verbose_name='Посилання на Instagram')),
                ('youtube', models.URLField(blank=True, default='', verbose_name='Посилання на YouTube')),
            ],
            options={
                'verbose_name': 'Налаштування контактів',
                'verbose_name_plural': '1. Контакти та Соцмережі',
            },
        ),
    ]
