# Generated by Django 6.0.5 on 2026-05-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_faqitem_pagetext_siteinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Опис')),
                ('icon', models.CharField(choices=[('ShieldCheck', 'Щит (безпека)'), ('Palette', 'Палітра (творчість)'), ('Smile', 'Усмішка'), ('Heart', 'Серце'), ('Star', 'Зірка'), ('Brain', 'Мозок'), ('Leaf', 'Листок'), ('Activity', 'Активність'), ('BookOpen', 'Книга'), ('Baby', 'Малюк'), ('Sun', 'Сонце'), ('Clock', 'Годинник'), ('CheckCircle2', 'Галочка')], default='ShieldCheck', max_length=30, verbose_name='Іконка')),
                ('color', models.CharField(choices=[('teal', 'Бірюзовий'), ('amber', 'Золотий'), ('rose', 'Рожевий'), ('blue', 'Синій'), ('green', 'Зелений'), ('emerald', 'Смарагдовий'), ('slate', 'Сірий')], default='rose', max_length=20, verbose_name='Колір')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': "Картка 'Про нас'",
                'verbose_name_plural': '3. Про нас - картки (3 шт)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DirectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Опис')),
                ('icon', models.CharField(choices=[('ShieldCheck', 'Щит (безпека)'), ('Palette', 'Палітра (творчість)'), ('Smile', 'Усмішка'), ('Heart', 'Серце'), ('Star', 'Зірка'), ('Brain', 'Мозок'), ('Leaf', 'Листок'), ('Activity', 'Активність'), ('BookOpen', 'Книга'), ('Baby', 'Малюк'), ('Sun', 'Сонце'), ('Clock', 'Годинник'), ('CheckCircle2', 'Галочка')], default='Brain', max_length=30, verbose_name='Іконка')),
                ('color', models.CharField(choices=[('teal', 'Бірюзовий'), ('amber', 'Золотий'), ('rose', 'Рожевий'), ('blue', 'Синій'), ('green', 'Зелений'), ('emerald', 'Смарагдовий'), ('slate', 'Сірий')], default='blue', max_length=20, verbose_name='Колір')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Напрямок',
                'verbose_name_plural': '4. Напрямки розвитку',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PremiseSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок слайду')),
                ('desc', models.CharField(max_length=300, verbose_name='Короткий опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='premises/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Слайд приміщення',
                'verbose_name_plural': '5. Приміщення - слайди (з фото)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва групи')),
                ('age', models.CharField(max_length=50, verbose_name='Вік')),
                ('desc', models.TextField(verbose_name='Опис')),
                ('icon', models.CharField(choices=[('ShieldCheck', 'Щит (безпека)'), ('Palette', 'Палітра (творчість)'), ('Smile', 'Усмішка'), ('Heart', 'Серце'), ('Star', 'Зірка'), ('Brain', 'Мозок'), ('Leaf', 'Листок'), ('Activity', 'Активність'), ('BookOpen', 'Книга'), ('Baby', 'Малюк'), ('Sun', 'Сонце'), ('Clock', 'Годинник'), ('CheckCircle2', 'Галочка')], default='Baby', max_length=30, verbose_name='Іконка')),
                ('color', models.CharField(choices=[('teal', 'Бірюзовий'), ('amber', 'Золотий'), ('rose', 'Рожевий'), ('blue', 'Синій'), ('green', 'Зелений'), ('emerald', 'Смарагдовий'), ('slate', 'Сірий')], default='teal', max_length=20, verbose_name='Колір')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Найпопулярніша (виділяється)')),
                ('popular_label', models.CharField(default='Найпопулярніша', max_length=50, verbose_name="Текст бейджу 'найпопулярніша'")),
                ('features', models.TextField(default='5-разове харчування\nПрогулянки щодня\nВсі гуртки включено', verbose_name='Особливості (кожна з нового рядка)')),
                ('btn_text', models.CharField(default='Обрати групу', max_length=50, verbose_name='Текст кнопки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вікова група',
                'verbose_name_plural': '6. Вікові групи',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Питання (FAQ)', 'verbose_name_plural': '7. Питання та Відповіді'},
        ),
        migrations.AlterModelOptions(
            name='pagetext',
            options={'verbose_name': 'Тексти сторінок', 'verbose_name_plural': '2. Тексти розділів'},
        ),
        migrations.AddField(
            model_name='faqitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='about_kicker',
            field=models.CharField(default='Про наш садок', max_length=100, verbose_name='Про нас: Маленький заголовок зверху'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='contact_form_btn',
            field=models.CharField(default='Відправити', max_length=50, verbose_name='Контакти: Текст кнопки'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='contact_form_title',
            field=models.CharField(default='Написати нам', max_length=100, verbose_name='Контакти: Заголовок форми'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='directions_kicker',
            field=models.CharField(default='Розвиток', max_length=100, verbose_name='Напрямки: Маленький заголовок'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='directions_title',
            field=models.CharField(default='Наші ключові напрямки', max_length=200, verbose_name='Напрямки: Заголовок'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='faq_title',
            field=models.CharField(default='Відповіді на часті питання', max_length=200, verbose_name='FAQ: Заголовок'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='hero_ai_btn_text',
            field=models.CharField(default='Є питання? Запитай ШІ-помічника', max_length=100, verbose_name='Головна: Текст кнопки ШІ'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='hero_badge_label',
            field=models.CharField(default='Досвіду та любові', max_length=100, verbose_name='Головна: Бейдж - підпис'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='hero_badge_value',
            field=models.CharField(default='15+ років', max_length=50, verbose_name='Головна: Бейдж - число'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='hero_btn_primary',
            field=models.CharField(default='Детальніше про нас', max_length=50, verbose_name='Головна: Текст першої кнопки'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='hero_btn_secondary',
            field=models.CharField(default='Контакти', max_length=50, verbose_name='Головна: Текст другої кнопки'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Головна: Фото'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='hero_title_accent',
            field=models.CharField(default='щастя', help_text='Це слово/фраза з заголовку буде підсвічено кольором', max_length=50, verbose_name='Головна: Виділене слово в заголовку (виділяється кольором)'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='premises_desc',
            field=models.TextField(default='Ми створили середовище, де сучасний дизайн поєднується з домашнім затишком. Кожне приміщення в нашому садку — це світлий та привітний простір, де малюки почуваються вільно та спокійно. Завдяки розумному плануванню, ігрові зони залишаються відкритими для активного руху.', verbose_name='Приміщення: Опис'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='premises_subtitle',
            field=models.CharField(default='Простір ЗДО №52: безпека та комфорт у кожній деталі.', max_length=300, verbose_name='Приміщення: Підзаголовок'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='premises_title',
            field=models.CharField(default='Приміщення', max_length=100, verbose_name='Приміщення: Заголовок'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='services_kicker',
            field=models.CharField(default='Вікові групи', max_length=100, verbose_name='Групи: Маленький заголовок'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='services_title',
            field=models.CharField(default='Оберіть свій формат', max_length=200, verbose_name='Групи: Заголовок'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='footer_copyright',
            field=models.CharField(default='Заклад дошкільної освіти №52 м. Рівного. Всі права захищено.', max_length=300, verbose_name='Футер: текст копірайту'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='nav_brand',
            field=models.CharField(default='ЗДО', max_length=50, verbose_name='Навігація: основна назва'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='nav_brand_accent',
            field=models.CharField(default='№52', max_length=50, verbose_name='Навігація: виділена частина'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='nav_cta_text',
            field=models.CharField(default='Заповнити анкету', max_length=50, verbose_name='Навігація: текст кнопки'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='map_url',
            field=models.TextField(blank=True, default='', verbose_name='Посилання на карту (тільки src з iframe Google Maps)'),
        ),
    ]
