# Generated by Django 6.0.5 on 2026-05-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_seed_default_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionCollageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(choices=[(1, 'Верхнє (портрет 1920×2880)'), (2, 'Середнє (ландшафт 1920×1280)'), (3, 'Нижнє (портрет 1920×2880)')], unique=True, verbose_name='Позиція')),
                ('image', models.ImageField(upload_to='directions/', verbose_name='Фото')),
                ('alt', models.CharField(blank=True, default='', max_length=200, verbose_name='Опис (alt)')),
            ],
            options={
                'verbose_name': 'Фото колажу (Напрямки - ряд 2)',
                'verbose_name_plural': '4б. Напрямки: фото колажу (ряд 2)',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DirectionGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='directions/', verbose_name='Фото (бажано 16:9)')),
                ('alt', models.CharField(blank=True, default='', max_length=200, verbose_name='Опис (alt)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фото каруселі (Напрямки - ряд 1)',
                'verbose_name_plural': '4а. Напрямки: фото каруселі (ряд 1)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='directioncard',
            options={'ordering': ['group', 'order', 'id'], 'verbose_name': 'Напрямок', 'verbose_name_plural': '4. Напрямки розвитку'},
        ),
        migrations.AddField(
            model_name='directioncard',
            name='group',
            field=models.CharField(choices=[('first', 'Перший ряд (картки зліва, карусель фото 16:9 справа)'), ('second', 'Другий ряд (колаж 3 фото зліва, картки справа)')], default='first', max_length=10, verbose_name='Ряд'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='logo_footer',
            field=models.ImageField(blank=True, help_text='Рекомендовано: білий/світлий логотип для темного фону', null=True, upload_to='logo/', verbose_name='Логотип у футері'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='logo_navbar',
            field=models.ImageField(blank=True, help_text='Рекомендовано: логотип для світлого фону (з текстом)', null=True, upload_to='logo/', verbose_name='Логотип у шапці'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='map_url',
            field=models.TextField(blank=True, default='', verbose_name='Посилання на карту (тільки URL з src iframe Google Maps, без [ ])'),
        ),
    ]
