# Generated by Django 6.0.5 on 2026-05-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seed_logos_and_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetext',
            name='about_highlights',
            field=models.TextField(blank=True, default='', help_text='Короткі тези списком (з галочками). Кожна теза з нового рядка.', verbose_name="Про нас: Тези (необов'язково; кожна з нового рядка)"),
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='about_desc',
            field=models.TextField(default='ЗДО №52 — це інноваційний простір безпечного розвитку. Наша головна мета — формування умов для гармонійного зростання вихованців та підтримка батьків у адаптації дитини.', help_text='Розділіть на абзаци натисканням Enter. Кожен абзац буде окремим блоком тексту.', verbose_name='Про нас: Опис (кожен абзац з нового рядка)'),
        ),
    ]
