# Generated by Django 6.0.5 on 2026-05-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pagetext_about_highlights_alter_pagetext_about_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Анкета', 'verbose_name_plural': 'Анкети (Заявки)'},
        ),
        migrations.AddField(
            model_name='surveyapplication',
            name='allergies',
            field=models.TextField(blank=True, default='', verbose_name='Алергії'),
        ),
        migrations.AddField(
            model_name='surveyapplication',
            name='challenges',
            field=models.TextField(blank=True, default='', verbose_name='Виклики у вихованні'),
        ),
        migrations.AddField(
            model_name='surveyapplication',
            name='expectations',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Що найважливіше'),
        ),
        migrations.AddField(
            model_name='surveyapplication',
            name='formula',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Чи є у раціоні дитяча суміш'),
        ),
        migrations.AddField(
            model_name='surveyapplication',
            name='interaction_formats',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Бажані формати взаємодії'),
        ),
        migrations.AddField(
            model_name='surveyapplication',
            name='lectures_interest',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Інтерес до лекцій/онлайн-сесій'),
        ),
        migrations.AddField(
            model_name='surveyapplication',
            name='parent_questions',
            field=models.TextField(blank=True, default='', verbose_name='Питання, які хочуть обговорити'),
        ),
        migrations.AddField(
            model_name='surveyapplication',
            name='pediatrist',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Потреба у періодичному педіатрі'),
        ),
        migrations.AddField(
            model_name='surveyapplication',
            name='red_flags',
            field=models.TextField(blank=True, default='', verbose_name='«Червоні прапорці»'),
        ),
        migrations.AddField(
            model_name='surveyapplication',
            name='time_slots',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Часові проміжки'),
        ),
        migrations.AddField(
            model_name='surveyapplication',
            name='value_in_comm',
            field=models.TextField(blank=True, default='', verbose_name='Найцінніше у комунікації з простором'),
        ),
        migrations.AlterField(
            model_name='surveyapplication',
            name='age_group',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Вік дитини (може бути декілька)'),
        ),
        migrations.AlterField(
            model_name='surveyapplication',
            name='benefits',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Пільги (інформованість)'),
        ),
        migrations.AlterField(
            model_name='surveyapplication',
            name='days',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Дні тижня'),
        ),
        migrations.AlterField(
            model_name='surveyapplication',
            name='e_queue',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Електронна черга'),
        ),
        migrations.AlterField(
            model_name='surveyapplication',
            name='format',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Формат перебування (може бути декілька)'),
        ),
    ]
