# Generated by Django 6.0.5 on 2026-05-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_surveyapplication_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='youtube',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='telegram',
            field=models.URLField(blank=True, default='', verbose_name='Посилання на Telegram'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='threads',
            field=models.URLField(blank=True, default='', verbose_name='Посилання на Threads'),
        ),
    ]
