# Generated by Django 6.0.5 on 2026-05-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_seed_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetext',
            name='hero_desc',
            field=models.TextField(default='Сучасний заклад дошкільної освіти у Рівному. Ми поєднуємо професійний догляд, безпеку та інноваційні методики для гармонійного розвитку вашого малюка.', help_text="Підказки оформлення:\n• Кожен абзац — з нового рядка (натисніть Enter).\n• Перший абзац буде великим виділеним 'лідом' з лівою бірюзовою рисочкою.\n• Щоб підкреслити важливе — обгорніть слово/фразу подвійними зірочками: **ваш текст**. Воно стане жирним і виділиться кольором.\nПриклад: «Сучасний заклад **дошкільної освіти** у Рівному»", verbose_name='Головна: Опис'),
        ),
    ]
