# Generated by Django 6.0.5 on 2026-05-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_workflow_and_clean_survey'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='api_contact_status_4cd228_idx',
            old_name='api_msg_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='surveyapplication',
            new_name='api_surveya_status_9bfa14_idx',
            old_name='api_survey_status_created_idx',
        ),
        migrations.AlterField(
            model_name='aboutcard',
            name='color',
            field=models.CharField(choices=[('teal', '🩵 Бірюзовий'), ('amber', '🟡 Золотий'), ('rose', '🌸 Рожевий'), ('blue', '🔵 Синій'), ('green', '🟢 Зелений'), ('emerald', '💚 Смарагдовий'), ('slate', '⚪ Сірий')], default='rose', max_length=20, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='aboutcard',
            name='icon',
            field=models.CharField(choices=[('ShieldCheck', '🛡 Щит (безпека)'), ('Palette', '🎨 Палітра (творчість)'), ('Smile', '🙂 Усмішка'), ('Heart', '❤️ Серце'), ('Star', '⭐ Зірка'), ('Brain', '🧠 Мозок'), ('Leaf', '🍃 Листок'), ('Activity', '📈 Активність'), ('BookOpen', '📖 Книга'), ('Baby', '👶 Малюк'), ('Sun', '☀️ Сонце'), ('Clock', '🕐 Годинник'), ('CheckCircle2', '✅ Галочка')], default='ShieldCheck', max_length=30, verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Внутрішні нотатки для команди. Відвідувач їх НЕ бачить.', verbose_name='Нотатки адміністратора'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='Автоматично стає «так», коли ви відкриваєте заявку.', verbose_name='Переглянуто'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', '🆕 Нова'), ('in_progress', '📞 В роботі'), ('contacted', "✅ Зв'язались"), ('enrolled', '🎉 Зараховано'), ('rejected', '🚫 Відмова'), ('archived', '📦 Архів')], db_index=True, default='new', help_text='Де зараз ця заявка у вашому процесі. Змінюйте по мірі роботи.', max_length=20, verbose_name='Статус обробки'),
        ),
        migrations.AlterField(
            model_name='directioncard',
            name='color',
            field=models.CharField(choices=[('teal', '🩵 Бірюзовий'), ('amber', '🟡 Золотий'), ('rose', '🌸 Рожевий'), ('blue', '🔵 Синій'), ('green', '🟢 Зелений'), ('emerald', '💚 Смарагдовий'), ('slate', '⚪ Сірий')], default='blue', max_length=20, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='directioncard',
            name='icon',
            field=models.CharField(choices=[('ShieldCheck', '🛡 Щит (безпека)'), ('Palette', '🎨 Палітра (творчість)'), ('Smile', '🙂 Усмішка'), ('Heart', '❤️ Серце'), ('Star', '⭐ Зірка'), ('Brain', '🧠 Мозок'), ('Leaf', '🍃 Листок'), ('Activity', '📈 Активність'), ('BookOpen', '📖 Книга'), ('Baby', '👶 Малюк'), ('Sun', '☀️ Сонце'), ('Clock', '🕐 Годинник'), ('CheckCircle2', '✅ Галочка')], default='Brain', max_length=30, verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='color',
            field=models.CharField(choices=[('teal', '🩵 Бірюзовий'), ('amber', '🟡 Золотий'), ('rose', '🌸 Рожевий'), ('blue', '🔵 Синій'), ('green', '🟢 Зелений'), ('emerald', '💚 Смарагдовий'), ('slate', '⚪ Сірий')], default='teal', max_length=20, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='icon',
            field=models.CharField(choices=[('ShieldCheck', '🛡 Щит (безпека)'), ('Palette', '🎨 Палітра (творчість)'), ('Smile', '🙂 Усмішка'), ('Heart', '❤️ Серце'), ('Star', '⭐ Зірка'), ('Brain', '🧠 Мозок'), ('Leaf', '🍃 Листок'), ('Activity', '📈 Активність'), ('BookOpen', '📖 Книга'), ('Baby', '👶 Малюк'), ('Sun', '☀️ Сонце'), ('Clock', '🕐 Годинник'), ('CheckCircle2', '✅ Галочка')], default='Baby', max_length=30, verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='surveyapplication',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Внутрішні нотатки для команди. Відвідувач їх НЕ бачить.', verbose_name='Нотатки адміністратора'),
        ),
        migrations.AlterField(
            model_name='surveyapplication',
            name='ages',
            field=models.JSONField(blank=True, default=list, help_text='Список обраних вікових діапазонів (може бути кілька — для кількох дітей).', verbose_name='Вік дитини'),
        ),
        migrations.AlterField(
            model_name='surveyapplication',
            name='benefits',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Поінформованість про пільги'),
        ),
        migrations.AlterField(
            model_name='surveyapplication',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='Автоматично стає «так», коли ви відкриваєте заявку.', verbose_name='Переглянуто'),
        ),
        migrations.AlterField(
            model_name='surveyapplication',
            name='parent_questions',
            field=models.TextField(blank=True, default='', verbose_name='Питання для обговорення'),
        ),
        migrations.AlterField(
            model_name='surveyapplication',
            name='status',
            field=models.CharField(choices=[('new', '🆕 Нова'), ('in_progress', '📞 В роботі'), ('contacted', "✅ Зв'язались"), ('enrolled', '🎉 Зараховано'), ('rejected', '🚫 Відмова'), ('archived', '📦 Архів')], db_index=True, default='new', help_text='Де зараз ця заявка у вашому процесі. Змінюйте по мірі роботи.', max_length=20, verbose_name='Статус обробки'),
        ),
        migrations.AlterField(
            model_name='surveyapplication',
            name='value_in_comm',
            field=models.TextField(blank=True, default='', verbose_name='Найцінніше у комунікації'),
        ),
    ]
