# Generated by Django 6.0.5 on 2026-05-30 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_sync_choices_helptext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcard',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Картка «Про нас»', 'verbose_name_plural': '«Про нас» — картки переваг'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Повідомлення', 'verbose_name_plural': 'Повідомлення з форми'},
        ),
        migrations.AlterModelOptions(
            name='directioncard',
            options={'ordering': ['group', 'order', 'id'], 'verbose_name': 'Напрямок розвитку', 'verbose_name_plural': 'Напрямки: картки-тези'},
        ),
        migrations.AlterModelOptions(
            name='directioncollageimage',
            options={'ordering': ['position'], 'verbose_name': 'Фото колажу (Напрямки, ряд 2)', 'verbose_name_plural': 'Напрямки: фото колажу (ряд 2)'},
        ),
        migrations.AlterModelOptions(
            name='directiongalleryimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Фото каруселі (Напрямки, ряд 1)', 'verbose_name_plural': 'Напрямки: фото каруселі (ряд 1)'},
        ),
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Питання (FAQ)', 'verbose_name_plural': 'Питання та відповіді (FAQ)'},
        ),
        migrations.AlterModelOptions(
            name='pagetext',
            options={'verbose_name': 'Тексти розділів', 'verbose_name_plural': 'Тексти розділів'},
        ),
        migrations.AlterModelOptions(
            name='premiseslide',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Слайд приміщення', 'verbose_name_plural': 'Приміщення — слайди (з фото)'},
        ),
        migrations.AlterModelOptions(
            name='servicegroup',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Вікова група', 'verbose_name_plural': 'Вікові групи'},
        ),
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name': 'Контакти та соцмережі', 'verbose_name_plural': 'Контакти та соцмережі'},
        ),
        migrations.AlterModelOptions(
            name='surveyapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка з анкети', 'verbose_name_plural': 'Заявки з анкети'},
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='email',
            field=models.EmailField(default='zdo52@ukr.net', help_text='Клікається для написання листа.', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='phone',
            field=models.CharField(default='+38 (0362) 12-34-56', help_text='Показується на сайті та клікається для дзвінка. Формат: +38 (097) 123-45-67.', max_length=25, validators=[django.core.validators.RegexValidator(message='Введіть коректний номер: лише цифри, пробіли та символи + ( ) -. Наприклад: +38 (097) 123-45-67', regex='^[\\d\\s()+\\-]{7,25}$')], verbose_name='Телефон'),
        ),
    ]
