# Generated by Django 6.0.5 on 2026-05-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_clean_labels_and_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=32, unique=True, verbose_name='Chat ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name="Ім'я у Telegram")),
                ('is_active', models.BooleanField(default=True, verbose_name='Отримує сповіщення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Підписався')),
            ],
            options={
                'verbose_name': 'Telegram-підписник',
                'verbose_name_plural': 'Telegram-сповіщення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name="Ім'я автора")),
                ('relation', models.CharField(blank=True, default='', max_length=100, verbose_name='Хто це (напр. «мама Софійки»)')),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name="Фото (необов'язково)")),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=5, verbose_name='Оцінка')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано на сайті')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки батьків',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.AddField(
            model_name='pagetext',
            name='testimonials_kicker',
            field=models.CharField(default='Відгуки', max_length=100, verbose_name='Відгуки: Маленький заголовок'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='testimonials_title',
            field=models.CharField(default='Що кажуть батьки', max_length=200, verbose_name='Відгуки: Заголовок'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='ga_measurement_id',
            field=models.CharField(blank=True, default='', help_text="Необов'язково. Вставте ваш GA4 ідентифікатор виду G-XXXXXXXXXX, щоб увімкнути аналітику відвідувачів. Порожньо — аналітика вимкнена.", max_length=20, verbose_name='Google Analytics ID'),
        ),
    ]
