# Generated by Django 6.0.5 on 2026-05-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_telegramsubscriber_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramsubscriber',
            options={'ordering': ['-is_admin', '-created_at'], 'verbose_name': 'Користувач Telegram', 'verbose_name_plural': 'Telegram: користувачі та права'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='handled_by',
            field=models.CharField(blank=True, default='', help_text='Хто з адміністраторів останнім змінив статус (зокрема з Telegram).', max_length=150, verbose_name='Опрацьовує'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='source',
            field=models.CharField(choices=[('site', '🌐 Сайт'), ('telegram', '✈️ Telegram')], db_index=True, default='site', help_text='Звідки надійшло звернення.', max_length=20, verbose_name='Джерело'),
        ),
        migrations.AddField(
            model_name='surveyapplication',
            name='handled_by',
            field=models.CharField(blank=True, default='', help_text='Хто з адміністраторів останнім змінив статус (зокрема з Telegram).', max_length=150, verbose_name='Опрацьовує'),
        ),
        migrations.AddField(
            model_name='surveyapplication',
            name='source',
            field=models.CharField(choices=[('site', '🌐 Сайт'), ('telegram', '✈️ Telegram')], db_index=True, default='site', help_text='Звідки надійшло звернення.', max_length=20, verbose_name='Джерело'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='is_admin',
            field=models.BooleanField(db_index=True, default=False, help_text="Увімкніть, щоб надати цій людині права адміністратора в боті: сповіщення про звернення та керування ними. Людина має спершу написати боту /start (тоді тут з'явиться її запис).", verbose_name='Адміністратор (повний доступ)'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон (поділився в боті)'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='state',
            field=models.CharField(blank=True, default='idle', max_length=30),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='state_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='@username'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_contact',
            field=models.CharField(blank=True, default='', help_text='Телефон / @username автора (для відгуків із Telegram).', max_length=150, verbose_name='Контакт автора'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='source',
            field=models.CharField(choices=[('site', '🌐 Сайт'), ('telegram', '✈️ Telegram')], default='site', max_length=20, verbose_name='Джерело'),
        ),
        migrations.AlterField(
            model_name='telegramsubscriber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Перша взаємодія'),
        ),
        migrations.AlterField(
            model_name='telegramsubscriber',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Для адміністраторів: чи слати сповіщення.', verbose_name='Отримує сповіщення'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Відгуки з Telegram надходять неопублікованими — спочатку модерація.', verbose_name='Опубліковано на сайті'),
        ),
    ]
