# Generated by Django 6.0.5 on 2026-05-30 19:06

from django.db import migrations, models


def _convert_statuses(apps, schema_editor):
    """Старі статуси → нові: enrolled/contacted → done; archived → done + is_archived."""
    for model_name in ("SurveyApplication", "ContactMessage"):
        M = apps.get_model("api", model_name)
        M.objects.filter(status__in=["enrolled", "contacted"]).update(status="done")
        M.objects.filter(status="archived").update(status="done", is_archived=True)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_telegramsubscriber_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='photo',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Закриті звернення автоматично йдуть в архів через кілька днів, щоб не заважати. Можна також архівувати/розархівувати вручну.', verbose_name='В архіві'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='tg_messages',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='surveyapplication',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Закриті звернення автоматично йдуть в архів через кілька днів, щоб не заважати. Можна також архівувати/розархівувати вручну.', verbose_name='В архіві'),
        ),
        migrations.AddField(
            model_name='surveyapplication',
            name='tg_messages',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', '🆕 Нова'), ('in_progress', '📞 В роботі'), ('done', '✅ Опрацьовано'), ('rejected', '🚫 Відмова')], db_index=True, default='new', help_text='Де зараз ця заявка у вашому процесі. Змінюйте по мірі роботи.', max_length=20, verbose_name='Статус обробки'),
        ),
        migrations.AlterField(
            model_name='surveyapplication',
            name='status',
            field=models.CharField(choices=[('new', '🆕 Нова'), ('in_progress', '📞 В роботі'), ('done', '✅ Опрацьовано'), ('rejected', '🚫 Відмова')], db_index=True, default='new', help_text='Де зараз ця заявка у вашому процесі. Змінюйте по мірі роботи.', max_length=20, verbose_name='Статус обробки'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='relation',
            field=models.CharField(blank=True, default='', help_text='Підпис під відгуком — чий з батьків і чиєї дитини.', max_length=100, verbose_name='Хто це (напр. «мама Софійки»)'),
        ),
        migrations.RunPython(_convert_statuses, _noop),
    ]
